general:
  test_size: 0.3
  random_state: 42
  cv: 5

PCA:
  n_components: 2

classifiers:
  RandomForest:
    type: rf
    grid_params:
      n_estimators: [20, 50, 70]
      max_depth: [3, 5, 7]
  GradientBoosting:
    type: gb
    grid_params:
      n_estimators: [5, 10, 20, 50, 100]
      max_depth: [2, 3, 5, 7, 10]
      learning_rate: [0.01, 0.25, 0.5]
  XGBoost:
    type: xgb
    grid_params:
      n_estimators: [75, 100, 125]
      max_depth: [1, 2, 3]
      learning_rate: [0.01, 0.25, 0.5]
  DecisionTree:
    type: dt
    grid_params:
      max_depth: [3, 5, 7]
